# comment
on:
  pull_request: {}
  push:
    branches: ["master", "main"]
  
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        publishToken: 11e1093817925793e39590682248f62daf72d720b42e9a4a3fa2d030e9bc666f
